### ISSUE TITLE
trait JavaModuleTests in trait JavaModule is deprecated

### ISSUE THREAD

**Issue by asarkar** [com-lihaoyi/mill#3385] opened 2024-08-19 02:43 UTC
```
[warn] /path/to/project/scala/out/mill-build/generateScriptSources.dest/millbuild/build.sc:13:32: trait JavaModuleTests in trait JavaModule is deprecated (since Mill 0.11.10): Use JavaTests instead
[warn]     _root_.mill.define.Discover[build]
[warn]                                ^
[warn] one warning found
```

scala% cat .mill-version 
0.11.11

**Comment by lihaoyi** [comment] 2024-08-19 02:47
Duplicate of https://github.com/com-lihaoyi/mill/issues/3371, should be fixed master and go out in the next release

**Comment by asarkar** [comment] 2024-08-19 02:50
@lihaoyi Thanks for the response. I did search in open issues before creating the ticket, but it seems like the duplicate issue was already closed, so, didn't find it. Sorry about that.

**Comment by lihaoyi** [comment] 2024-08-19 02:52
@asarkar no worries! Please open issues with whatever you find, any feedback is definitely welcome

**Comment by lihaoyi** [comment] 2024-10-09 16:04
This has re-appeared in master, still looking into why

**Closed** 2024-10-10 13:31 UTC
