### ISSUE TITLE
Windows BSP: `request failed: buildTarget/dependencySources` - cannot import into IDE - forward slash is prepended to the paths for some reason

### ISSUE THREAD

**Issue by ScalaWilliam** [com-lihaoyi/mill#1283] opened 2021-04-18 17:14 UTC
Hi, I installed mill via scoop on my Windows 10 machine, JDK 16; `build.sc` is as follows:

```
import mill._
import scalalib._
object foo extends ScalaModule {
  def scalaVersion = "2.13.5"
}
```

Building with mill works; then I run `mill mill.bsp.BSP/install`, and import the project via IntelliJ's BSP support.

After import, it shows this:
![image](https://user-images.githubusercontent.com/2464813/115154149-4ee04000-a071-11eb-99d4-845d6e0c40af.png)

I am very keen on mill however last time I tried it it also had some other loading issue (pre-BSP times though iirc).

Stack trace:

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Dev/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib_2.13/0.9.6/mill-scalalib_2.13-0.9.6-sources.jar
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:230)
    at java.base/java.nio.file.Path.of(Path.java:147)
    at java.base/java.nio.file.Paths.get(Paths.java:69)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:484)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:483)
    at os.Path$.apply(Path.scala:382)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10(ModuleUtils.scala:131)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10$adapted(ModuleUtils.scala:131)
    at scala.collection.StrictOptimizedIterableOps.filterImpl(StrictOptimizedIterableOps.scala:226)
    at scala.collection.StrictOptimizedIterableOps.filterImpl$(StrictOptimizedIterableOps.scala:221)
    at scala.collection.immutable.ArraySeq.filterImpl(ArraySeq.scala:35)
    at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:217)
    at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:217)
    at scala.collection.immutable.ArraySeq.filter(ArraySeq.scala:35)
    at mill.bsp.ModuleUtils$.getMillBuildClasspath(ModuleUtils.scala:131)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetDependencySources$2(MillBuildServer.scala:136)
    at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:638)
    at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
    at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetDependencySources$1(MillBuildServer.scala:134)
    at mill.bsp.MillBuildServer.handleExceptions(MillBuildServer.scala:495)
    at mill.bsp.MillBuildServer.buildTargetDependencySources(MillBuildServer.scala:129)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    ... 10 more



Apr 18, 2021 6:04:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError

SEVERE: Internal error: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/OpenJDK/src.zip

java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/OpenJDK/src.zip
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2178)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
    at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:91)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:831)

Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/OpenJDK/src.zip
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:230)
    at java.base/java.nio.file.Path.of(Path.java:147)
    at java.base/java.nio.file.Paths.get(Paths.java:69)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:484)
    at os.PathConvertible$StringConvertible$.apply(Path.scala:483)
    at os.Path$.apply(Path.scala:382)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10(ModuleUtils.scala:131)
    at mill.bsp.ModuleUtils$.$anonfun$getMillBuildClasspath$10$adapted(ModuleUtils.scala:131)
    at scala.collection.StrictOptimizedIterableOps.filterImpl(StrictOptimizedIterableOps.scala:226)
    at scala.collection.StrictOptimizedIterableOps.filterImpl$(StrictOptimizedIterableOps.scala:221)
    at scala.collection.immutable.ArraySeq.filterImpl(ArraySeq.scala:35)
    at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:217)
    at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:217)
    at scala.collection.immutable.ArraySeq.filter(ArraySeq.scala:35)
    at mill.bsp.ModuleUtils$.getMillBuildClasspath(ModuleUtils.scala:131)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetScalacOptions$2(MillBuildServer.scala:394)
    at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:638)
    at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:634)
    at scala.collection.AbstractIterable.foldLeft(Iterable.scala:920)
    at mill.bsp.MillBuildServer.$anonfun$buildTargetScalacOptions$1(MillBuildServer.scala:391)
    at mill.bsp.MillBuildServer.handleExceptions(MillBuildServer.scala:495)
    at mill.bsp.MillBuildServer.buildTargetScalacOptions(MillBuildServer.scala:386)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
    at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
    ... 10 more

```

**Comment by lefou** [comment] 2021-04-18 17:55
Duplicate of #1092 .

**Closed** 2021-04-18 17:57 UTC
Labels: duplicate
