### ISSUE TITLE
Mill special syntaxes to import plugins and contrib modules doesn't work anymore

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2474] opened 2023-04-27 13:23 UTC
```scala
import $ivy.`com.github.lolgab::mill-crossplatform::0.2.1`
```

should desugar to:
```scala
import $ivy.`com.github.lolgab::mill-crossplatform_mill0.11.0-M8:0.2.1`
```

but, instead, desugars to:
```scala
import $ivy.`com.github.lolgab::mill-crossplatform:0.2.1`
```

Moreover:
```scala
import $ivy.`com.lihaoyi::mill-contrib-bloop:`
```

doesn't desugar anymore to:
```scala
import $ivy.`com.lihaoyi::mill-contrib-bloop:$MILL_VERSION`
```

**Comment by lefou** [comment] 2023-04-27 15:44
Partial duplicate of #2457,but this once covers also the platform, hence I'll close the other one as duplicate.

**Closed** 2023-04-29 21:44 UTC
