### ISSUE TITLE
[Feature Request] Better output for mill show

### ISSUE THREAD

**Issue by Avimitin** [com-lihaoyi/mill#2880] opened 2023-11-17 10:06 UTC
Currently our team is using mill to run a large number of build tasks, with each one returning the final binary path wrapped inside the `PathRef` type. These binaries are used in the final main task. But because the amount of these binaries are too large, so we decide to use `mill -i -j0 show _.<our_task_name>` to compile the build tasks simultaneously and use the return JSON to index those file, then package them together for distribution.

And here are some problems we encounter during the `mill show` and parsing process:

1. Using `-j0` can help us build all the tasks using all cores, but it will also add a prefix `#[<number>]`  to the stdout, and cause the output JSON to be invalid. Now, to get the valid JSON, we can only use regex expression to trim the prefix.
2. Because we are trying to package these binaries, we run mill inside a clean chroot. So every time we rebuild the package, mill will write "Preparing Java <version> runtime, this might take one or two minutes.." to stdout, which will also break the output JSON. Our workaround is to run `mill -i resolve _ > /dev/null` to do a warm-up.
3. Using `mill show` on the `PathRef` type will return a string with path and other metadata, so we need split the string with ':' and get the last segment.

> Here is the real build script we are using to make the mill show work as expect
>
>  ![image](https://github.com/com-lihaoyi/mill/assets/30021675/607e0788-4b36-4e86-9644-235e22f9bef3)

Here is some of my idea for improving the mill show command:

1. using stdout to print JSON can help bash command line processing but is not reliable, so can we have a new option (like `-o`) to let `mill show` write the JSON output to a file?
2. Is it possible to let `PathRef` output path only?

**Comment by lihaoyi** [comment] 2023-11-19 01:34
> Is it possible to let PathRef output path only?

I think this is probably unlikely to be supported. `mill show` is meant to show the "raw" metadata, rather than any prettified version of it, and splitting it on a `:` is a small enough hardship in any JSON-processing environment that I don't think it's worth special casing in Mill here. Even `jq` has `| split(":")`. 

If you really want the raw paths from Mill, you can write your own target `def yourTaskNamePath = T{ yourTaskName().path }`, and `show` that to get them

We should fix everything else you brought up though. `show` output is meant to be clean. The fact that `#[thread-id]` and `Preparing Java runtime` are leaking into the `show` output is definitely not intended

**Comment by lihaoyi** [comment] 2023-11-19 02:10
Prefixing of `show` output should be fixed by https://github.com/com-lihaoyi/mill/pull/2884

w.r.t. `"Preparing Java runtime, this might take one or two minutes.."`, I haven't managed to reproduce it being printed to stdout. AFAICT, it goes to stderr https://github.com/com-lihaoyi/mill/blob/bc84d5b4c7932fe662eaa62248505818cf8f3a86/runner/src/mill/runner/MillMain.scala#L192. @Avimitin do you have a minimal repro of it going to the `stdout` stream?

**Comment by Avimitin** [comment] 2023-11-19 04:38
Yes, just run:

```bash
rm -r ~/.mill
mill -i -j0 show anything > stdout.txt
cat stdout.txt
```

**Comment by lihaoyi** [comment] 2023-11-19 07:16
@Avimitin got it! Looks like @lefou already fixed that in https://github.com/com-lihaoyi/mill/pull/2839, which is scheduled to go out in 0.11.6. So once https://github.com/com-lihaoyi/mill/pull/2884 lands, that's probably it for the actionable improvements on this ticket

**Comment by Avimitin** [comment] 2023-11-19 07:48
Thanks!

**Closed** 2023-11-19 11:13 UTC
