### ISSUE TITLE
Metals BSP and foreign modules invalidate caches when no dependency has changed

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2131] opened 2022-11-19 14:25 UTC
# Problem

I use [mill-scalablytyped](https://github.com/lolgab/mill-scalablytyped) in a foreign-module so I can perform the expensive (around ~1 minute) Typescript -> Scala compilation and the result doesn't get invalidated if I change `build.sc`. Using BSP is now invalidating the task randomly, spending 1 minute after just editing an unrelated Scala file, making it impossible to use.

# Reproduction (* needs metals and manual intervention)

```scala
// build.sc
import mill._
import mill.scalalib._
import $file.project.other

object foo extends ScalaModule {
  def scalaVersion = "2.13.10"
  def moduleDeps = Seq(other.bar)
}
```

```scala
// project/other.sc
import mill._
import mill.scalalib._

object bar extends ScalaModule {
  def scalaVersion = "2.13.10"
  def ivyDeps = T {
    println("START COMPUTING")
    Thread.sleep(2000)
    println("END COMPUTING")
    super.ivyDeps()
  }
}
```

You have to watch compile with:
```
mill -w -i -j 2 __.compile
```

Then you need to import the build on Metals using the BSP server.

Editing any Scala file like `foo/src/Main.scala` will print the `START COMPUTING` and `END COMPUTING` strings. This especially happens when the compilation fails.

**Comment by lefou** [comment] 2022-11-19 15:52
I can't reproduce. I also do not see any inlcude for mill-scalablytyped and it won't reproduce without any sources I guess. Can you provide a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example), please?

**Comment by lolgab** [comment] 2022-11-19 20:44
In my machine I can reproduce without any plugin.

> Editing any Scala file like `foo/src/Main.scala` will print the START COMPUTING and END COMPUTING strings. This especially happens when the compilation fails.

You need to edit a file with the path `foo/src/Main.scala` and you can write whatever you want, since it needs to fail the compilation.

> Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), please?

This is the best I could do, unfortunately :(

**Comment by lefou** [comment] 2022-11-21 09:15
I still can't reproduce. 

This is my file:

```scala
  GNU nano 6.4                                                                                            foo/src/Main.scala                                                                                                       
package example

// compile error
invalid code
```

After editing in vscode, I only see the exected recompilation output in Mill (in watch mode), but not any sign of re-evaluation of `ivyDeps`.

```
Watching for changes to 7 paths... (Enter to re-run, Ctrl-C to exit)
[#1] [63/63] foo.compile 
[#1] [info] compiling 1 Scala source to /tmp/mill-2/out/foo/compile.dest/classes ...
[#1] [error] /tmp/mill-2/foo/src/Main.scala:4:1: expected class or object definition
[#1] [error] invalid code
[#1] [error] ^
[#1] [error] one error found
1 targets failed
foo.compile Compilation failed
Watching for changes to 7 paths... (Enter to re-run, Ctrl-C to exit)
```

**Comment by ckipp01** [comment] 2022-11-21 11:01
Just piping in to say that I was curios if Metals was possibly requesting something that would force the foreign module to recompile, but in testing I also can't reproduce this.

**Comment by lolgab** [comment] 2022-11-21 12:08
I'll try to create a GIF that shows the process. Making the file compile and then fail the compilation maybe helps? Sorry for the very bad reproduction :(

**Comment by lefou** [comment] 2022-11-21 12:28
Producing a file which inially compiles successfully before I make a error-change doesn't help for me.

Is the `-j 2` important to reproduce? If yes, than you can't use `out/mill-profile.json` but `out/mill-par-profile.json` instead. It can be opened with `chrome://tracing` (which seem to be not zoomable nowadays for me), so you can also grep it for `"args": = ["cached"]` or `"dur": 0`

Do you use different JVM versions on CLI vs Metals? Maybe, there is something which affects the initial input hash, so any downstream target invalidates?

**Comment by lolgab** [comment] 2022-11-21 12:43
> Do you use different JVM versions on CLI vs Metals? Maybe, there is something which affects the initial input hash, so any downstream target invalidates?

You're a genius! It is exactly this! Thank you!!!
Now the following question is, is this the expected behavior? Should Mill or Metals warn you to use the same JVM to avoid this? What can we do to improve the situation?

**Comment by lefou** [comment] 2022-11-21 12:47
We should analyze where this dependency comes from and whether it is required at all or can be replaced by somewhat more appropriate. I know we are creating some hash from the classpath, to detect changes in the codebase. This probably catches JVM changes, too. Any idea hwo to reduce to a more minimal set to track are very welcome.

**Comment by lefou** [comment] 2022-11-22 08:08
Going to close this. If you want to open a feature request in the discussions, please go ahead.

**Closed by lefou** 2022-11-22 08:08 UTC
Labels: need-more-info
