### ISSUE TITLE
JNA error on Apple M1

### ISSUE THREAD

**Issue by bravomikekilo** [com-lihaoyi/mill#1399] opened 2021-07-07 16:23 UTC
Please don't open issues for questions, but ask in our gitter channel at https://gitter.im/lihaoyi/mill

Mill installations via `coursier` or `cs` are unsupported.

mill install using wrapper not working on Apple M1 machine, seems a jna related problem

> Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/baomingkun/Library/Caches/JNA/temp/jna3520450636097532474.tmp: dlopen(/Users/baomingkun/Library/Caches/JNA/temp/jna3520450636097532474.tmp, 1): no suitable image found.  Did find:
	/Users/baomingkun/Library/Caches/JNA/temp/jna3520450636097532474.tmp: no matching architecture in universal wrapper
	/Users/baomingkun/Library/Caches/JNA/temp/jna3520450636097532474.tmp: no matching architecture in universal wrapper
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:123)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:103)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:93)
	at mill.main.Server.$anonfun$run$2(MillServerMain.scala:89)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.main.Server$.lockBlock(MillServerMain.scala:201)
	at mill.main.Server.$anonfun$run$1(MillServerMain.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.main.Server$.tryLockBlock(MillServerMain.scala:208)
	at mill.main.Server.run(MillServerMain.scala:79)
	at mill.main.MillServerMain$.main(MillServerMain.scala:43)
	at mill.main.MillServerMain.main(MillServerMain.scala)
Exception in thread "main" java.lang.Exception: Failed to connect to server
	at mill.main.client.MillClientMain.run(MillClientMain.java:217)
	at mill.main.client.MillClientMain.main0(MillClientMain.java:146)
	at mill.main.client.MillClientMain.main(MillClientMain.java:99)

**Comment by lefou** [comment] 2021-07-08 09:35
Have you tried to run mill with `--no-server` option?

**Comment by bravomikekilo** [comment] 2021-07-09 19:24
--no-server works

**Comment by lefou** [comment] 2021-07-15 12:36
Duplicate of https://github.com/com-lihaoyi/mill/issues/1098

**Closed by lefou** 2021-07-15 12:36 UTC
Labels: duplicate, workaround-available
