### ISSUE TITLE
Support generalized `runBackground` for generic processes

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2654] opened 2023-07-05 12:36 UTC
`runBackground` allows running JVM applications in the background.
I would love to have the same thing for generic processes.
We have `Jvm.spawnSubprocess` which spawns a process in the background when `background = true` but we need to have something like our backgroundwrapper to run the process, poll on the various files generated in [backgroundSetup](https://github.com/com-lihaoyi/mill/blob/d72a6d7c781bab95be82244f1171ea73a81d24b9/scalalib/src/mill/scalalib/JavaModule.scala#L743) and then kill the process as `runBackground` does.

**Comment by lihaoyi** [comment] 2023-07-07 02:08
Duplicate of https://github.com/com-lihaoyi/mill/issues/657 I think

**Closed** 2023-07-07 06:51 UTC
