### ISSUE TITLE
Ability to run Node for tests in the directory of the script

### ISSUE THREAD

**Issue by nafg** [com-lihaoyi/mill#2143] opened 2022-11-25 03:27 UTC
I'm trying to do something similar to scalajs-bundler in https://github.com/nafg/mill-bundler. One issue I'm hitting is that it needs to generate a package.json and `npm install` somewhere under `out/`, but IIUC because it's running Node from the base directory it won't see `node_modules/`.

This is even worse for `JsDom`, because with `JsEnvConfig.NodeJs` I can override `fastLinkJSTest` to inject a bundling step, producing a script that doesn't need `node_modules` anymore. But IIRC `JsDom` will `require("jsdom")` outside the script.

**Comment by nafg** [comment] 2022-11-25 03:31
On second thought...

I edited the title, because maybe the solution is not to have a new setting or parameter to pass in the working directory. Maybe it should automatically use the script's location as the working directory.

Although, I guess most people currently maintain a `package.json` by hand in the root directory and manually `npm install`. So I guess for them tests should run in the base directory. So maybe it does have to be a setting or parameter?

**Comment by lefou** [comment] 2022-11-25 07:27
Typically in Mill, test run in a forked process and support the setting of `forkWorkingDir`. Unfortunately, `ScalaJSModule` currently does not support this setting.

* https://github.com/com-lihaoyi/mill/issues/1036

**Comment by lefou** [comment] 2022-11-25 07:29
Duplicate of #1036

**Closed by lefou** 2022-11-25 07:29 UTC
Labels: duplicate
