### ISSUE TITLE
`FileNotFoundException` on Windows caused by underlying coursier

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3563] opened 2024-09-16 13:23 UTC
Under Windows, I had the following cousier download issues. Rerunning seems to help, so it could be a race condition. Probably a regression.

CI build: https://github.com/com-lihaoyi/mill/actions/runs/10883643568/job/30197520523?pr=3560

```
1 targets failed
contrib.playlib.worker[2.6].resolvedRunIvyDeps java.io.FileNotFoundException: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\os-lib_2.12\0.10.7\os-lib_2.12-0.10.7.jar (The process cannot access the file because it is being used by another process)
```

**Comment by lefou** [comment] 2024-09-16 13:38
Retry-related, but a different exception:

https://github.com/com-lihaoyi/mill/actions/runs/10884321338/job/30199843323?pr=3562

```
scalalib.resolvedIvyDeps java.nio.file.AccessDeniedException: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-dynamic_2.13\3.8.3\.scalafmt-dynamic_2.13-3.8.3.jar__sha1.computed18409881239238064357.tmp -> C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-dynamic_2.13\3.8.3\.scalafmt-dynamic_2.13-3.8.3.jar__sha1.computed
```

**Comment by lefou** [comment] 2024-09-16 13:42
I think we should re-add Mills own retry mechanism until we can prove it's fixed in coursier. We could disable it via a feature-flag via an env variable, so that testing without retry-handling in Mill is easy. But for the better user experience, we better keep retry-handling in Mill for now. It doesn't hurt unless it's needed, then it's really helpful.

**Comment by alexarchambault** [comment] 2024-09-16 14:26
I should be able to have a look tomorrow Europe time (morning or afternoon, I'm not sure yet).

I'm not sure about defaulting to retries by default, unless it really hampers development on Mill for you right now. A benefit of removing them in Mill is precisely to unearth those issues, to fix the root cause (or at least, adding a retry right around where it should be added in coursier).

**Comment by alexarchambault** [comment] 2024-09-16 14:28
Post links to CI failures or stack traces here, the more we have, the better.

**Comment by lefou** [comment] 2024-09-16 15:14
Yeah, I agree in general. But the price pays the user. Wouldn't it be better to print out some big fat warning when we retry. That way, you can still see all issue but users don't end up with broken workflows. Some users reported these kind of issues for years, so I'd rather not mess with their user experience.

**Comment by lefou** [comment] 2024-09-16 15:22
https://github.com/com-lihaoyi/mill/actions/runs/10884997255/job/30201897400

**Comment by lefou** [comment] 2024-09-16 15:41
https://github.com/com-lihaoyi/mill/actions/runs/10886805575/job/30208048205

**Comment by alexarchambault** [comment] 2024-09-16 17:24
To precise my point of view, this has to be addressed before 0.12.0 final, so that Mill users at large don't pay its price. Or earlier if the impact on Mill development is too high. Else, it's best to notice when it happens IMO, so that it can be fixed properly.

**Comment by lihaoyi** [comment] 2024-09-16 17:49
Let's go ahead without Mill retries for now. If it remains a problem long term we can put them back, but the point of the RC period is to surface issues, and we don't have infra for out-of-band error reporting set up. For now we have reason to believe the issues can be fixed in a teasonable period of time so surfacing them is great. Unless they're really so painful that development is impossible because of them

**Comment by lefou** [comment] 2024-09-16 19:16
I hope for an upstream fix, I really do. I'm also tired of arguing this topic. To give some perspective: these upstream issues are known for years and I lost lots of work hours until I landed these workarounds. Experiencing these regressions is frustrating and unnecessary. I don't think our early adopters (me included) should experience these issues (again).

**Comment by lihaoyi** [comment] 2024-09-17 02:30
Hit another `AccessDeniedException` here https://github.com/com-lihaoyi/mill/actions/runs/10894796574/job/30232196351

**Comment by alexarchambault** [comment] 2024-09-17 15:33
I have hope that https://github.com/coursier/coursier/pull/3076 fixes that. It's being released right now.

**Closed** 2024-09-18 00:03 UTC
