### ISSUE TITLE
./Mill not working with m1 Mac (Failed to connect to server error)

### ISSUE THREAD

**Issue by GabeNicholson** [com-lihaoyi/mill#3016] opened 2024-02-17 21:25 UTC
I am trying to work with a build written in mill but whenever I run any mill command it fails. And there is always an Exception in thread "main" java.lang.Exception: Failed to connect to server error. Here is the output of my version. 

```
Mill Build Tool version 0.11.7
Java version: 21.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_CA, platform encoding: UTF-8
OS name: "Mac OS X", version: 14.2.1, arch: aarch64
```

Error code:

```
./mill
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/gabriel/Library/Caches/JNA/temp/jna14575276343731702839.tmp: dlopen(/Users/gabriel/Library/Caches/JNA/temp/jna14575276343731702839.tmp, 0x0001): tried: '/Users/gabriel/Library/Caches/JNA/temp/jna14575276343731702839.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabriel/Library/Caches/JNA/temp/jna14575276343731702839.tmp' (no such file), '/Users/gabriel/Library/Caches/JNA/temp/jna14575276343731702839.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1024)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:999)
	at com.sun.jna.Native.<clinit>(Native.java:191)
	at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:123)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:103)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:93)
	at mill.main.Server.$anonfun$run$2(MillServerMain.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.main.Server$.lockBlock(MillServerMain.scala:203)
	at mill.main.Server.$anonfun$run$1(MillServerMain.scala:84)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.main.Server$.tryLockBlock(MillServerMain.scala:210)
	at mill.main.Server.run(MillServerMain.scala:81)
	at mill.main.MillServerMain$.main(MillServerMain.scala:45)
	at mill.main.MillServerMain.main(MillServerMain.scala)
Exception in thread "main" java.lang.Exception: Failed to connect to server
	at mill.main.client.MillClientMain.run(MillClientMain.java:200)
	at mill.main.client.MillClientMain.main0(MillClientMain.java:129)
	at mill.main.client.MillClientMain.main(MillClientMain.java:82)
```

**Comment by lefou** [comment] 2024-02-18 09:58
Thanks for the report. I think we have other users working on m1 Macs, so it might be related to the Java version, which is 21. Maybe, other Mac users could verify and reproduce, that this is an issue?

**Comment by Quafadas** [comment] 2024-02-28 16:57
@GabeNicholson I'm on M2, but would expect similar behaviour?

```
simon@Simons-Mac-mini indigo2 % mill -v
Mill Build Tool version 0.11.7
Java version: 21.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "Mac OS X", version: 14.2.1, arch: aarch64
```

Any change there is shell configuration tripping you up?

**Comment by lefou** [comment] 2024-03-20 17:01
Thank you all for your input! Looks like you all already use Java 21 without issues (except the OP). I think there must be some other issue. 

I'm closing this, as I don't see any action to be taken. @GabeNicholson if you still experiencing this issue, please provide more details. How do you have installed `mill`. Do other Java apps work for you?

**Closed by lefou** 2024-03-20 17:01 UTC

**Comment by Roiocam** [comment] 2024-06-13 01:23
I have the same issue too, I am currently using m1 mac, and i tried jdk17 and jdk21 both not work for me.

```
~/IdeaProject/example-3 5s                                       09:18:51
❯ export JAVA_HOME=`/usr/libexec/java_home -v 17`
~/IdeaProject/example-3                                          09:19:03
❯ ./mill -v
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/roiocam/Library/Caches/JNA/temp/jna12902990016562179596.tmp: dlopen(/Users/roiocam/Library/Caches/JNA/temp/jna12902990016562179596.tmp, 0x0001): tried: '/Users/roiocam/Library/Caches/JNA/temp/jna12902990016562179596.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/roiocam/Library/Caches/JNA/temp/jna12902990016562179596.tmp' (no such file), '/Users/roiocam/Library/Caches/JNA/temp/jna12902990016562179596.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
```

**Comment by Roiocam** [comment] 2024-06-13 01:30
I guess because I am using a very old version... the latest 0.11.7 works on my local.

**Comment by lefou** [comment] 2024-06-13 14:55
In case you need to use an older version of Mill, you should always be able to fall back to `--no-server` or `--interactive` options, to switch Mill into a no-server mode.
