### ISSUE TITLE
Incorrect result of command argument parsing

### ISSUE THREAD

**Issue by ghostbuster91** [com-lihaoyi/mill#3005] opened 2024-02-07 11:04 UTC
## Actual behavior

Given following mill's command definition:

```scala
import mill._

def assembly(foo:String, bar: String) = T.command {
    println(s"foo '$foo' bar '$bar'")
}
```

If we try to call it without one of the arguments it will fail as expected:
```
./mill assembly --foo 123                                                                                          [build.sc] [47/53] zincReportCachedProblems
Missing argument: --bar <str>
Expected Signature: assembly
  --bar <str>
  --foo <str>
```

However, if we call it as follows:
```
./mill assembly --foo --bar 456                                                                                    [1/1] assembly
foo '--bar' bar '456'
```
we can see that mill didn't complain about missing value for `foo` and used `--bar` for it. 

## Expected behavior

I would expect mill to fail in the second case as the required value for `foo` argument was not provided. Alternatively an empty string should be assigned to `foo`, but it should not have the value `--bar` assigned.

repository with reproduction: https://github.com/ghostbuster91/demos/tree/mill-command
mill version: 0.11.7

**Comment by lihaoyi** [comment] 2024-02-07 11:18
This is a consequence of Mill turning on `positional = true` by default in Mainargs

This was done arbitrarily a long time ago (inherited from Ammonite, long before we standardized on Mainargs), and we've just kept the behavior ever since. It could be worth revisiting. @lefou do you have any thoughts?

**Comment by lihaoyi** [comment] 2024-02-19 01:40
Going to close this as not a bug for now, though we may want to change the behavior in future

**Closed by lihaoyi** 2024-02-19 01:40 UTC

**Comment by kubukoz** [comment] 2024-02-22 19:03
@lihaoyi can you reopen and close as "not planned"? ("closed as completed" is the default but it might be confusing here)
