### ISSUE TITLE
Import $file.folder.build fails when folder name contains hyphen

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [com-lihaoyi/mill#1788] opened 2022-03-18 19:49 UTC
## Description

When import build.sc from a folder whose name contains a hyphen, mill would fail to find it from its internal map 

## Reproduced version

0.10.1 and 0.10.2, while 0.10.0 is not affected

## MWE

```
.
├── a-b
│   └── build.sc
└── build.sc
```
Where in the toplevel `build.sc` is
```scala
import $file.`a-b`.build

def A = T {
  println("a")
}
```
and in the `a-b/build.sc` is
```scala
def B = T {
  println("b")
}
```
Run `mill -i -j 0 __.compile` would result in 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        ...
Caused by: java.util.NoSuchElementException: key not found: ammonite.$file.a-b.build
        ...
```

Note that changing the folder name `a-b` to `a` solves this issue.

## Additional notes

Personally I think this is related to #1663, but it is just a wild guess.

**Comment by cisen** [comment] 2022-03-19 01:04
This happened to me too

**Comment by sequencer** [comment] 2022-03-19 01:37
This happened to me too

**Comment by cisen** [comment] 2022-03-19 07:08
> This happened to me too

Downgrading mill's version to 0.9.8 resolved my issue

**Comment by lolgab** [comment] 2022-03-19 14:05
@ZenithalHourlyRate Thank you for opening this issue! It was indeed caused by #1663.
@cisen I think downgrading to `0.10.0` should be enough.

I have opened #1789 which should fix this.

**Comment by lolgab** [comment] 2022-03-21 10:10
Fixed in version [0.10.2-2-8c163c](https://github.com/com-lihaoyi/mill/releases/download/0.10.2/0.10.2-2-8c163c)

**Comment by lolgab** [comment] 2022-03-21 10:35
@sequencer Did you test it? Before releasing a version it would be nice to know if it fixes your use case.

**Comment by sequencer** [comment] 2022-03-21 10:39
@lolgab testing.

**Comment by sequencer** [comment] 2022-03-21 10:48
@lolgab opps...
still not work on my side.

**Comment by sequencer** [comment] 2022-03-21 11:03
I'm using https://github.com/sequencer/playground, which is quite huge, I'm trying to give a minimal reproducible bug later.

**Comment by ZenithalHourlyRate** [comment] 2022-03-21 11:27
> I'm using https://github.com/sequencer/playground, which is quite huge, I'll give a minimal reproducible bug later.

[0.10.2-2-8c163c](https://github.com/com-lihaoyi/mill/releases/download/0.10.2/0.10.2-2-8c163c) works for me on this repo.

**Comment by lefou** [comment] 2022-03-23 08:45
@sequencer It would be nice if you could report back, whether it issue is fixed for you in current main branch or not.

**Comment by sequencer** [comment] 2022-03-23 15:30
Sorry for the late reply!
It does work for me!
Thanks for @lolgab great work!

**Comment by lolgab** [comment] 2022-03-23 15:42
Nice, I'm closing this again 👍

**Closed by lolgab** 2022-03-23 15:42 UTC
Labels: bug

**Comment by sequencer** [comment] 2022-04-11 02:59
hi @lefou is possible to release a new version(0.10.3) to get rid of this bug? our flow strictly depends on the published version, which has been blocked for 20+ days.

**Comment by lefou** [comment] 2022-04-11 06:57
@sequencer Sure. Sorry for the delay, but we found and fixes some other issues as well, so we waited. I'd like to merge some other PRs today and then I can cut the next release.

**Comment by sequencer** [comment] 2022-04-11 06:59
Thanks! I believe I should improve our flow to support the pinning version as well. Sorry for this pushing.

**Comment by lefou** [comment] 2022-04-11 07:05
Technically speaking, each snapshot release we are publishing, is a real and correct release. It is publishing to Sonatype Central release repository and the version is based on the last tag plus the count of commits and the hash of the commit. I'm not aware of any technical difference which could prohibit the consumption of e.g. Mill `0.10.2-35-3ef3c1` unless you deploy some guard that rejects hyphens in the version number.

**Comment by sequencer** [comment] 2022-04-11 07:08
Yes. I understand this SNAPSHOT version can provide up to date version of mill. 
the flow I have been depending on is we use the mill packaging from a distro, while distro only publish the “stable” version, so that’s the tricky part…
