### ISSUE TITLE
Automatically exclude Mill transitive depedencies from build classpath

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#3207] opened 2024-06-14 12:32 UTC
Plugins should add Mill dependencies as `provided`, but sometimes they don't and Mill breaks when you update Mill to a newer version which adds new fields to traits.
Mill could solve the problem by automatically add exclusion rules for `mill-scalalib` and its other artifacts when adding dependencies to the build via `import $ivy.`.

**Comment by lolgab** [comment] 2024-06-14 13:00
This was already fixed in https://github.com/com-lihaoyi/mill/pull/3189.
I just triggered a new snapshot release for it.

**Comment by lolgab** [comment] 2024-06-14 14:04
I tried with the latest snapshot but it doesn't seem to be solved.
Reproduction:
```scala
// build.sc
import $ivy.`com.disneystreaming.smithy4s::smithy4s-mill-codegen-plugin::0.18.22`

import mill._
import mill.scalalib._

object root extends RootModule with ScalaModule {
  def scalaVersion = "3.4.2"
}
```

.mill-version
```
0.11.7-118-56323c
```

Errors with:
```
java.lang.AbstractMethodError: Receiver class millbuild.build$root$ does not define or inherit an implementation of the resolved method 'abstract mill.define.ModuleRef mill$scalalib$JavaModule$$super$zincWorker()' of interface mill.scalalib.JavaModule.
    mill.scalalib.JavaModule.zincWorker(JavaModule.scala:38)
    mill.scalalib.JavaModule.zincWorker$(JavaModule.scala:38)
    millbuild.build$root$.zincWorker(build.sc:27)
    mill.scalalib.ScalaModule.$anonfun$compile$1(ScalaModule.scala:287)
    scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:469)
    mill.moduledefs.Cacher.cachedTarget(Cacher.scala:10)
    mill.moduledefs.Cacher.cachedTarget$(Cacher.scala:9)
    mill.define.Module$BaseClass.cachedTarget(Module.scala:58)
    mill.scalalib.ScalaModule.compile(ScalaModule.scala:280)
    mill.scalalib.ScalaModule.compile$(ScalaModule.scala:280)
    millbuild.build$root$.compile(build.sc:27)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    mill.resolve.Resolve$.$anonfun$instantiateTarget$2(Resolve.scala:96)
```

**Comment by lefou** [comment] 2024-06-18 00:12
I guess to understand this issue better, we should draft an integration test for reproduction. Then we can try to fix this on Mill's side.

**Comment by lolgab** [comment] 2024-06-18 07:31
This seems related to https://github.com/com-lihaoyi/mill/issues/2985

**Comment by lefou** [comment] 2024-06-18 07:49
> This seems related to #2985

I don't think so. #2985 is explicitly bumping a dependency, which is supposed to be provided by Mill. This is different from resolving a transitive dependency.

**Comment by lefou** [comment] 2024-06-18 09:25
The issue is, the exclusion filter introduced in #3189 contains less mill modules and transitive dependencies then I thought, hence the filtering in incomplete.

**Closed** 2024-06-20 21:58 UTC
Labels: bug
