### ISSUE TITLE
mill is not resistant to the coursier cache being deleted

### ISSUE THREAD

**Issue by pieter-bos** [com-lihaoyi/mill#2845] opened 2023-10-20 15:23 UTC
```scala
import mill._

object test extends Module {
  def task = T { 0 }
}
```

(All commands below with `--no-server` so we are not tricked by already loaded classpaths; ./mill here is millw 0.4.6 in case that matters)

When I evaluate this task for the very first time mill lets me know it's compiling the compiler interface:

```
$ ./mill --no-server show test.task
[build.sc] [48/52] compile 
Compiling compiler interface...
[info] compiling 1 Scala source to /home/pieter/mill-examples/deleteCache/out/mill-build/compile.dest/classes ...
[info] done compiling
[1/1] show > [1/1] test.task 
0
```

If I now delete the whole coursier cache, mill will no longer start. Maybe this is a bit brutish, but it seems like something you may want to do :)

```
$ rm -rf ~/.cache/coursier/
$ ./mill --no-server show test.task
[build.sc] [24/52] mill.scalalib.ZincWorkerModule.worker 
1 targets failed
mill.scalalib.ZincWorkerModule.worker java.lang.ClassNotFoundException: mill.scalalib.worker.ZincWorkerImpl
    java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:35)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    mill.scalalib.ZincWorkerModule.$anonfun$worker$3(ZincWorkerModule.scala:60)

```

I can repair this situation by removing `out/mill-build/mill`:

```
$ rm -rf out/mill-build/mill
$ ./mill --no-server show test.task
[1/1] show 
0
```

In case it's useful to you, it seems that specifically `mill-scalalib-worker_2.13` is expected to be in the cache; removing any other cached artifact just re-downloads the artifact:

```
$ rm -rf ~/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/
$ ./mill --no-server show test.task
[build.sc] [24/52] mill.scalalib.ZincWorkerModule.worker 
1 targets failed
mill.scalalib.ZincWorkerModule.worker java.lang.ClassNotFoundException: mill.scalalib.worker.ZincWorkerImpl
    java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:35)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    mill.scalalib.ZincWorkerModule.$anonfun$worker$3(ZincWorkerModule.scala:60)
```

```
# arbitrary other seemingly important artifact
$ rm -rf ~/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-main-api_2.13/
$ ./mill --no-server show test.task
[1/1] show 
0
```

**Comment by lihaoyi** [comment] 2023-10-22 02:54
I think we can close this as working as intended. There is nothing we can do against people selectively deleting files. Either you let Mill manage the files or you wipe out everything and start clean

**Comment by lefou** [comment] 2023-10-22 08:56
As coursier uses a cache and we refer to files inside that cache, and cleaning large caches from time to time is a reasonable action, we should try to handle this kind of errors. In fact, we already handle that for all normal ivy dependencies, by setting the `revalidate` flag to `Revalidate.Once`. But we forgot to do it when we load mill project modules. I created PR #2846, to fix that.

**Closed** 2023-10-22 18:42 UTC
